"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent

# Load env from repo root first, then optional backend/.env overrides
load_dotenv(PROJECT_ROOT / ".env")
load_dotenv(BASE_DIR / ".env")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

if not SECRET_KEY:
    if os.getenv("DEBUG", "False").lower() == "true":
        SECRET_KEY = "django-insecure-local-dev-only-change-me"
    else:
        raise ValueError("SECRET_KEY environment variable is required for production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

APP_MODE = os.getenv("APP_MODE", "PROD")

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    "nested_admin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "phonenumbers",
    "django_ckeditor_5",
    "corsheaders",
    "users",
    "courses",
    "progress",
    "quiz",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

db_engine = os.getenv("DB_ENGINE")
if not db_engine:
    db_engine = "sqlite" if DEBUG else "mysql"
db_engine = db_engine.lower()

if db_engine in {"mysql", "mariadb"}:
    database_engine = "django.db.backends.mysql"
    default_port = "3306"
    db_socket = os.getenv("DB_SOCKET", "").strip()
    database_options = {
        "charset": "utf8mb4",
    }
    if db_socket:
        database_options["unix_socket"] = db_socket
elif db_engine in {"postgres", "postgresql"}:
    database_engine = "django.db.backends.postgresql"
    default_port = "5432"
    database_options = {}
elif db_engine == "sqlite":
    database_engine = "django.db.backends.sqlite3"
    default_port = ""
    database_options = {}
else:
    raise ValueError(
        "Unsupported DB_ENGINE. Use one of: mysql, mariadb, postgres, postgresql, sqlite"
    )

if database_engine == "django.db.backends.sqlite3":
    DATABASES = {
        "default": {
            "ENGINE": database_engine,
            "NAME": os.getenv("DB_NAME", str(BASE_DIR / "db.sqlite3")),
        }
    }
else:
    db_host = os.getenv("DB_HOST", "localhost")
    db_port = os.getenv("DB_PORT", default_port)

    if (
        database_engine == "django.db.backends.mysql"
        and "unix_socket" in database_options
    ):
        # Force socket auth when DB_SOCKET is configured.
        db_host = ""
        db_port = ""

    DATABASES = {
        "default": {
            "ENGINE": database_engine,
            "NAME": os.getenv("DB_NAME", "lms_db"),
            "USER": os.getenv("DB_USER", "django"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": db_host,
            "PORT": db_port,
            "OPTIONS": database_options,
        }
    }


if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
CORS_ALLOW_CREDENTIALS = True

SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", default=not DEBUG)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "DENY"
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "staticfiles"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "500/hour",
        "otp": "5/minute",
        "login": "10/minute",
    },
}

if DEBUG and APP_MODE == "DEV":
    REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"].insert(0, "backend.authentication.DevModeAuthentication")

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

AUTH_USER_MODEL = "users.User"

MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = BASE_DIR / "media"

CERTIFICATE_STORAGE_BACKEND = os.getenv("CERTIFICATE_STORAGE_BACKEND", "local")
DUMMY_CERTIFICATE_PNG_PATH = os.getenv(
    "DUMMY_CERTIFICATE_PNG_PATH",
    str(MEDIA_ROOT / "certificates" / "dummy.png"),
)

CKEDITOR_5_UPLOAD_PATH = "uploads/"
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": {
            "toolbar_panel_id": "toolbar",
            "toolbar_width": "100%",
            "items": [
                "undo",
                "redo",
                "|",
                "heading",
                "|",
                "bold",
                "italic",
                "underline",
                "strikethrough",
                "|",
                "alignment",
                "fontFamily",
                "fontColor",
                "fontBackgroundColor",
                "|",
                "link",
                "imageUpload",
                "mediaEmbed",
                "fileUpload",
                "|",
                "bulletedList",
                "numberedList",
                "todoList",
                "|",
                "blockQuote",
                "insertTable",
                "codeBlock",
                "code",
                "|",
                "findAndReplace",
                "highlight",
                "removeFormat",
            ],
            "shouldNotGroupWhenFull": True,
        },
        "language": "en",  # set any language you want
        "image": {
            "toolbar": ["imageTextAlternative", "imageStyle:full", "imageStyle:side"]
        },
        "table": {"contentToolbar": ["tableColumn", "tableRow", "mergeTableCells"]},
        "placeholder": "Enter Your Text...",
    }
}

# ============================================================================
# Email Configuration (SMTP — GoDaddy, Gmail, etc.)
# ============================================================================
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

if DEBUG and not EMAIL_HOST_USER:
    # Local testing without SMTP credentials — OTP still returned in API when DEBUG=True
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", default=EMAIL_PORT == 465)
    EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", default=not EMAIL_USE_SSL)

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@easyoptionlearning.com")

# Feedback recipient email
FEEDBACK_RECIPIENT = os.getenv(
    "FEEDBACK_RECIPIENT", os.getenv("DEFAULT_FROM_EMAIL", "")
)

# ============================================================================
# SMS OTP — Moplet (trader-tactical) + optional Fortius (Hostinger production)
# ============================================================================
MOPLET_API_KEY = os.getenv("MOPLET_API_KEY", "")
MOPLET_SENDER_ID = os.getenv("MOPLET_SENDER_ID", "MOPLET")

SMS_API_URL = os.getenv("SMS_API_URL", "https://smsfortius.org/V2/")
SMS_API_KEY = os.getenv("SMS_API_KEY", "")
SMS_SENDER_ID = os.getenv("SMS_SENDER_ID", "")
SMS_OTP_TEMPLATE_ID = os.getenv("SMS_OTP_TEMPLATE_ID", "")
# Leave blank to use trader-tactical default TradeMaster OTP text in users/sms.py
SMS_OTP_MESSAGE_TEMPLATE = os.getenv("SMS_OTP_MESSAGE_TEMPLATE", "")
