# Generated by Django 6.0 on 2026-02-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_userstreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstreak',
            name='current_streak',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userstreak',
            name='longest_streak',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
