# Generated by Django 6.0 on 2026-03-15 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_lesson_objective_module_icon"),
        ("progress", "0004_alter_userstreak_current_streak_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image_file",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[("local", "Local"), ("remote", "Remote")],
                        default="local",
                        max_length=20,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-issued_at",),
                "unique_together": {("user", "course")},
            },
        ),
    ]
