# Generated by Django 6.0 on 2026-02-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='objective',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
