# Generated by Django 6.0 on 2026-03-22

from django.db import migrations
import django_ckeditor_5.fields


def migrate_takeaways_to_key_takeaway(apps, schema_editor):
    Lesson = apps.get_model("courses", "Lesson")
    LessonTakeaway = apps.get_model("courses", "LessonTakeaway")

    lesson_ids = (
        LessonTakeaway.objects.values_list("lesson_id", flat=True).distinct().iterator()
    )

    for lesson_id in lesson_ids:
        takeaway_texts = list(
            LessonTakeaway.objects.filter(lesson_id=lesson_id)
            .order_by("id")
            .values_list("text", flat=True)
        )
        if not takeaway_texts:
            continue

        html = "<ul>" + "".join(f"<li>{text}</li>" for text in takeaway_texts) + "</ul>"
        Lesson.objects.filter(id=lesson_id).update(key_takeaway=html)


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_lesson_objective_module_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="objective",
            new_name="lesson_objective",
        ),
        migrations.AddField(
            model_name="lesson",
            name="common_mistakes",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, config_name="default", default=""
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="key_takeaway",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, config_name="default", default=""
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="practical_task",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, config_name="default", default=""
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_objective",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, config_name="default", default=""
            ),
        ),
        migrations.AlterField(
            model_name="lessonfaq",
            name="answer",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, config_name="default", default=""
            ),
        ),
        migrations.RunPython(
            migrate_takeaways_to_key_takeaway,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name="LessonTakeaway",
        ),
    ]
