# Generated by Django 6.0 on 2026-03-22

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_lesson_rich_sections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                config_name="default",
                default="",
            ),
        ),
    ]
