# Generated by Django 5.2.6 on 2026-07-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_pricing_and_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='title',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('NISM', 'NISM')], max_length=100),
        ),
    ]
