# Generated by Django 6.0 on 2026-01-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=45),
        ),
    ]
