# Generated by Django 6.0 on 2026-02-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('trader', 'Full-time Trader'), ('professional', 'Finance Professional'), ('entrepreneur', 'Entrepreneur'), ('employee', 'Salaried Employee'), ('business', 'Business Owner'), ('investor', 'Investor'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
