# Generated by Django 6.0 on 2026-03-22 14:06

from django.db import migrations, models


OLD_INDEX_NAME = "users_passw_email_46bd14_idx"
NEW_INDEX_NAME = "users_passw_email_b4e79e_idx"


def _index_names(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(
            cursor, table_name
        )
    return {name for name, constraint in constraints.items() if constraint["index"]}


def rename_index_forward(apps, schema_editor):
    PasswordResetOTP = apps.get_model("users", "PasswordResetOTP")
    table_name = PasswordResetOTP._meta.db_table
    index_names = _index_names(schema_editor, table_name)

    if NEW_INDEX_NAME in index_names:
        return

    if OLD_INDEX_NAME in index_names:
        schema_editor.remove_index(
            PasswordResetOTP,
            models.Index(fields=["email", "-created_at"], name=OLD_INDEX_NAME),
        )

    schema_editor.add_index(
        PasswordResetOTP,
        models.Index(fields=["email", "-created_at"], name=NEW_INDEX_NAME),
    )


def rename_index_backward(apps, schema_editor):
    PasswordResetOTP = apps.get_model("users", "PasswordResetOTP")
    table_name = PasswordResetOTP._meta.db_table
    index_names = _index_names(schema_editor, table_name)

    if OLD_INDEX_NAME in index_names:
        return

    if NEW_INDEX_NAME in index_names:
        schema_editor.remove_index(
            PasswordResetOTP,
            models.Index(fields=["email", "-created_at"], name=NEW_INDEX_NAME),
        )

    schema_editor.add_index(
        PasswordResetOTP,
        models.Index(fields=["email", "-created_at"], name=OLD_INDEX_NAME),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rename_index_forward, rename_index_backward),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='passwordresetotp',
                    new_name=NEW_INDEX_NAME,
                    old_name=OLD_INDEX_NAME,
                ),
            ],
        ),
    ]
