# Generated by Django 6.0 on 2026-03-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='users_passw_email_b4e79e_idx',
            old_name='users_passw_email_46bd14_idx',
        ),
    ]
